trigger: 
  branches:
    include:
      - feature/*
      - main
      
pool: Prabhas-Agent-Pools

variables:
  directory_config: '$(System.DefaultWorkingDirectory)/todoapp_parent'
  service_conn: 'PrabhaSC-WIF'

steps:
- task: TerraformInstaller@1
  displayName: Terrafomr Install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(directory_config)
    backendServiceArm: $(service_conn)
    backendAzureRmStorageAccountName: 'krishnastg5678'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'prod.terraform.tfstate'

- task: TerraformTask@5
  displayName: Terraform Fmt
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(directory_config)'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'PrabhaSC-WIF'

- task: TerraformTask@5
  displayName: Terrafomr Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: $(directory_config)

- task: TerraformTask@5
  displayName: Terrafomr Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(directory_config)
    environmentServiceNameAzureRM: $(service_conn)

- task: ManualValidation@1
  inputs:
    notifyUsers: 'prabhakarnayak993@gmail.com'
    approvers: 'nayakprabhakar073@gmail.com'
    instructions: 'check kar do'

# Apply will run only if branch is 'main' after reviewer approve
- task: TerraformTask@5
  displayName: Terraoform Apply
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: $(directory_config)
    environmentServiceNameAzureRM: $(service_conn)